### PR TITLE
adds ike-prow-plugins services

### PR DESCRIPTION
**Pull request by MatousJobanek**
Adds ike-prow-plugins services. The templates are here https://github.com/arquillian/ike-prow-plugins/tree/master/cluster
PR that adds build-master job to the ci.centos.org is here https://github.com/openshiftio/openshiftio-cico-jobs/pull/661

### CODE REVIEW

**Comment by kbsingh** [comment]
attn: @jmelis  @mmclanerh

**Comment by xyntrix** [comment]
@MatousJobanek Thank you for the PR!  I apologize if I've missed some prior communication. Could you go over briefly what this is and why it needs to be merged in here? I have a basic understanding of Prow (I think.. maybe..) but I don't have a solid context around what Ike is, or what Ike + Prow are together.

If this a new sentry plugin, we probably should include it with the sentry container build (sentry-sso), referenced here: https://github.com/CentOS/container-index/blob/master/index.d/centos.yaml#L1256 and here https://github.com/CentOS/CentOS-Dockerfiles/tree/master/sentry-sso/centos7/8.22  or think about add a sentry-openshiftio omnibus container.

If we're looking to build a standalone sentry-pod for the purpose of a specific plugin, we should think of ways to not require the extra footprint that might take up in favor of just packing that plugin with all the rest -- and if necessary, the right knobs to  scale up replicas when load demands it. If I'm waaaay off on what's we're looking to achieve here, I do apologize in advance and welcome the knowledge. The docs page for ike-prow-plugins doesn't actually describe what it is, what it's for, etc..

**Comment by MatousJobanek** [comment]
Hi @mmclanerh 
ike-prow-plugins project is set of PR automation plugins (plus the prow hook) that listens on a webhook and checks:
* that every feature is shipped with automated tests - done by [test-keeper](http://arquillian.org/ike-prow-plugins/#_test_keeper_plugin) plugin
* if the work on a proposed PR is still work in progress (according to title prefix or label) or is finished and ready to review - done by [work-in-progress](http://arquillian.org/ike-prow-plugins/#_work_in_progress_plugin) plugin
* that description and title matches predefined template and contains all necessary information - done by test-sanitizer plugin that is not yet implemented so not part of this PR

All projects that are using the plugins are listed here https://github.com/arquillian/ike-prow-plugins/blob/master/cluster/osio-plugins.yaml

This is not a Sentry plugin and is not anyhow related to the Sentry. The reason why I sent the PR here is a previous discussion with @kbsingh and other folks where KB proposed that the plugins could live next to Sentry as it is "artistically the same sort of scope".

**Comment by jmelis** [comment]
@MatousJobanek thanks a lot for the explanation, it clarifies lots of things.

I have some questions:

- Where is it currently deployed? Will we need to coordinate to sunset the current deployment and start this one?
- Does this deployment need a database to hold state?
- What about DNS? Do we need to modify some records?
- Do we need routes or secrets? Note that saasherder filters out both and we need to define them separately.
- From what I can tell the images are CentOS based, if we want to deploy them to production they should be RHEL based. This is something we can help with cc @riuvshin

**Comment by MatousJobanek** [comment]
> Where is it currently deployed? 

it is on Bartosz's tenant

> Will we need to coordinate to sunset the current deployment and start this one?

I don't think so. When the new one is running then I'll change the webhook in the related projects and that should be all.

> Does this deployment need a database to hold state?

no, it doesn't hold any state

> What about DNS? Do we need to modify some records?

I don't think so

> Do we need routes or secrets? Note that saasherder filters out both and we need to define them separately.

Yes, I was about to create a new issue in HK to ask for config map and secrets creation but I wasn't sure who I could send the secrets to and I also need to clarify the values of the secrets that will be used in prod. It should be clear today. Just for your information, we have two config maps and three secrets (gh token, webhook secret and sentry dsn)

> From what I can tell the images are CentOS based, if we want to deploy them to production they should be RHEL based. This is something we can help with cc @riuvshin

Yes, it is CentOS based. From the discussion we had, I got the feeling that the RHEL requirement is not so urgent, but that was one month ago. So I'll create another Dockerfile that will be `prod.registry.devshift.net/osio-prod/base/pcp:latest` based and use it in the CD cico script.

**Comment by jmelis** [comment]
> > What about DNS? Do we need to modify some records?
> 
> I don't think so

I assume you will be using the url for the webhook as exposed by the route in the OpenShift cluster?

> > Do we need routes or secrets? Note that saasherder filters out both and we need to define them separately.
> 
> Yes, I was about to create a new issue in HK to ask for config map and secrets creation but I wasn't sure who I could send the secrets to and I also need to clarify the values of the secrets that > will be used in prod. It should be clear today. Just for your information, we have two config maps and three secrets (gh token, webhook secret and sentry dsn)> 

Sound perfect!

> > From what I can tell the images are CentOS based, if we want to deploy them to production they should be RHEL based. This is something we can help with cc @riuvshin
> 
> Yes, it is CentOS based. From the discussion we had, I got the feeling that the RHEL requirement is not so urgent, but that was one month ago. So I'll create another Dockerfile that will be > `prod.registry.devshift.net/osio-prod/base/pcp:latest` based and use it in the CD cico script. 

Please cc in that PR so I can review it too!

**Comment by jmelis** [comment]
Just for completeness sake, we will need to also enable `extra_target: rhel` in the ci-centos index.

**Comment by MatousJobanek** [comment]
> I assume you will be using the url for the webhook as exposed by the route in the OpenShift cluster?

Yes, we need the webhook url, but I'm not sure if that requires any DNS change. Anyway, this brings me to the fact that the url will probably start with `errortracking.prod-preview.openshift.io`, so some prefix eg.: `ike` would be awesome. My knowledge in this area is very limited, so sorry for my weird/incomplete/vague answers :-).

> Please cc in that PR so I can review it too!

here is PR to our repo: https://github.com/arquillian/ike-prow-plugins/pull/149 feel free to review it and comment anything that is wrong

> Just for completeness sake, we will need to also enable extra_target: rhel in the ci-centos index.

modified PR: https://github.com/openshiftio/openshiftio-cico-jobs/pull/661/commits/6dacf1da8d49b1ea664c44ae82007b553df448ae

**Review by jmelis — CHANGES_REQUESTED** [review]
REGISTRY should be `prod.registry.devshift.net/osio-prod`

**Review by jmelis — CHANGES_REQUESTED** [review]
This will be deployed into staging. Can you please replace all `hash: ...` with `hash: none`?

This will not change anything effectively but it will ensure that there is no confusion as to whether this is deployed in prod.

EDIT: just to clarify - this is not strictly necessary, but it will lead to less confusion down the line.

**Review by jmelis — APPROVED** [review]
LGTM

**Pull request merged**
